package edu.buffalo.cse.cse486586.simpledynamo;

/**
 * Created by keno on 4/21/15.
 */
public enum MType {
    RESULT, INSERT, QUERY, DELETE, QUERYALL, DELETEALL,
    TRANSFER, DELETE_REPLICA, INSERTREPLICA, INSERT_REPLICA, QUERY_REPLICA, VOID, ACK, LOCAL, INSERTED, QUERY_RESULT, PRINTLOCAL, REJECT, BACKUP_INSERT, REPLICA_RESULT, DELETED, WAKE
}
